name: brl_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  auto_route: ^7.8.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dio_smart_retry: ^5.0.0
  duration: ^3.0.13
  flash: ^3.0.5+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.1
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.0.0
  intl: any
  platform_info: ^4.0.2
  responsive_framework: ^1.1.1
  talker_dio_logger: ^2.3.0
  talker_flutter: ^3.3.1
  velocity_x: ^4.1.1

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  riverpod_lint: ^2.1.1
  riverpod_test: ^0.1.3
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true
  generate: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
